import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const c=await browser.newContext({serviceWorkers:'block'}),p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
// UI-only fixtures. Real authorization is tested separately in the Firestore emulator.
const auth=`export const inMemoryPersistence={};const user={uid:'admin-test',email:'minmaung0307@gmail.com',getIdTokenResult:async()=>({claims:{email_verified:true,email:'minmaung0307@gmail.com'},signInProvider:'google.com',authTime:new Date().toISOString()})};const auth={currentUser:user};export const getAuth=()=>auth;export const setPersistence=async()=>{};export const onAuthStateChanged=(auth,cb)=>{cb(auth.currentUser);return ()=>{}};export class GoogleAuthProvider{setCustomParameters(){}};export const signInWithPopup=async()=>({user});export const reauthenticateWithPopup=signInWithPopup;export const signOut=async()=>{auth.currentUser=null};`;
const cloud=`let rows=new Map(),seq=0;const snapshot=id=>({id,exists:()=>rows.has(id),data:()=>rows.get(id)});const sdk={collection:()=>({}),doc:(...args)=>({id:args.length===3?args[2]:'new'+(++seq)}),getDocFromServer:async()=>({exists:()=>false}),orderBy:()=>{},limit:()=>{},startAfter:()=>{},query:()=>{},serverTimestamp:()=>({seconds:Date.now(),nanoseconds:0}),getDocsFromServer:async()=>({docs:[...rows.keys()].map(snapshot),size:rows.size}),runTransaction:async(db,fn)=>fn({get:async ref=>snapshot(ref.id),set:(ref,data)=>rows.set(ref.id,data),delete:ref=>rows.delete(ref.id)})};export const getCloud=async()=>({app:{},db:{},sdk});export const cloudEventsEnabled=true;export const publishedEvents=async()=>[{title:'Live fixture event',templeName:'Community',city:'Austin',state:'TX',address:'Test address',dateStart:'2026-12-01',dateEnd:'2026-12-01',description:'<script>unsafe text</script>',status:'published'}];`;
await c.route('**/*',r=>{const u=new URL(r.request().url());if(u.pathname.endsWith('/cloud.js'))return r.fulfill({contentType:'text/javascript',body:cloud});if(u.pathname.endsWith('/firebase-auth.js'))return r.fulfill({contentType:'text/javascript',body:auth});if(!['localhost','127.0.0.1'].includes(u.hostname))return r.abort();return r.continue();});
const base=process.env.TMF_URL||'http://127.0.0.1:8766';await p.goto(base+'/admin.html');await p.waitForFunction(()=>!document.querySelector('#signIn').disabled);assert.equal(await p.locator('#adminWorkspace').isVisible(),false);await p.locator('#signIn').click();await p.locator('#eventForm').waitFor({state:'visible'});
for(const [key,value]of Object.entries({title:'Test published event',templeName:'Test temple',city:'Austin',state:'TX',address:'Test address',dateStart:'2026-12-01'}))await p.locator(`[name=${key}]`).fill(value);
await p.locator('[name=status]').selectOption('published');await p.locator('#saveEvent').click();await p.waitForFunction(()=>document.querySelector('#saveStatus').textContent.startsWith('Published.'));assert.match(await p.locator('#adminEvents').innerText(),/Test published event/);
await p.getByRole('button',{name:'Edit',exact:true}).click();await p.locator('[name=status]').selectOption('archived');await p.locator('#saveEvent').click();await p.waitForFunction(()=>document.querySelector('#adminEvents').textContent.includes('archived'));
await p.locator('#importSuggestion').setInputFiles({name:'suggestion.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({type:'tmf-suggestion',subject:'Imported event',from_name:'Private Sender',reply_to:'private@example.com',message:'Public info'}))});await p.waitForFunction(()=>document.querySelector('[name=title]').value==='Imported event');assert.equal(await p.locator('[name=status]').inputValue(),'draft');assert.ok(!(await p.locator('#eventForm').innerText()).includes('private@example.com'));
for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'admin overflow '+width);}
await p.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';window.scrollTo(0,0)});await p.waitForTimeout(500);
if(process.env.SCREENSHOT_DIR)await p.screenshot({path:process.env.SCREENSHOT_DIR+'/admin-desktop.png',fullPage:true});
await p.locator('#signOut').click();assert.equal(await p.locator('#adminWorkspace').isVisible(),false);
await p.goto(base+'/#events');await p.waitForFunction(()=>document.querySelector('#eventGrid').textContent.includes('Live fixture event'));assert.match(await p.locator('#eventGrid').innerText(),/<script>unsafe text<\/script>/);assert.equal(await p.locator('#eventGrid script').count(),0);assert.deepEqual(errors,[]);
console.log('PASS: mocked admin sign-in, publish, archive, suggestion import, sign-out, four responsive sizes; public cloud merge and text escaping. Real access rules tested separately.');await browser.close();
