import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const context=await browser.newContext({serviceWorkers:'block',viewport:{width:1280,height:1000}});const page=await context.newPage();const errors=[];const external=[];page.on('pageerror',e=>errors.push(e.message));
// External services are blocked. Search must still work, and tiles are mocked, not fetched in bulk.
await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname==='127.0.0.1'||u.hostname==='localhost')return route.continue();external.push(u.hostname);return route.abort();});
const base=process.env.TMF_URL||'http://127.0.0.1:8766';await page.goto(base);await page.waitForSelector('.place-card');
assert.ok(!external.some(x=>/googleapis|emailjs/.test(x)));
await page.locator('#search').fill('Sitagu');await page.locator('#searchForm').evaluate(f=>f.requestSubmit());await page.waitForFunction(()=>!document.querySelector('#templeList').hasAttribute('aria-busy'));assert.match(await page.locator('#templeList').innerText(),/Sitagu Buddhist Vihara/);
await page.locator('#search').fill('သီတဂူ');await page.locator('#searchForm').evaluate(f=>f.requestSubmit());await page.waitForFunction(()=>!document.querySelector('#templeList').hasAttribute('aria-busy'));assert.match(await page.locator('#templeList').innerText(),/Sitagu/);
await page.locator('#resetFilters').click();await page.locator('[data-category=organization]').click();await page.waitForFunction(()=>!document.querySelector('#templeList').hasAttribute('aria-busy'));assert.ok(await page.locator('.place-card').count()>0);
await page.locator('#search').fill('zzzzzz-no-place');await page.locator('#searchForm').evaluate(f=>f.requestSubmit());await page.waitForFunction(()=>!document.querySelector('#templeList').hasAttribute('aria-busy'));assert.match(await page.locator('#templeList').innerText(),/Not in this directory yet/);
await page.locator('#resetFilters').click();await page.waitForSelector('.place-card');await page.locator('#mapToggle').click();assert.equal(await page.locator('#map').isVisible(),true);assert.ok(await page.locator('.leaflet-interactive').count()>0);await page.locator('#mapToggle').click();
await page.getByRole('link',{name:'Events',exact:true}).click();await page.waitForSelector('.event-card');assert.equal(await page.locator('.event-card').count(),3);
await page.getByRole('link',{name:'Contribute',exact:false}).click();await page.locator('[name=from_name]').fill('Test');await page.locator('[name=subject]').fill('Test suggestion');await page.locator('[name=message]').fill('Test only');await page.getByRole('button',{name:'Send for review'}).click();await page.waitForFunction(()=>!document.querySelector('#submitForm').inert);assert.equal(await page.locator('[name=message]').inputValue(),'Test only');assert.equal(await page.locator('a[href^="mailto:"]').count(),0);
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});for(const section of ['discover','events','submit']){await page.goto(base+'#'+section);await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),section+' overflow at '+width);}}
await page.setViewportSize({width:1440,height:1000});await page.goto(base+'?q=Sitagu#discover');await page.waitForSelector('.place-card');if(process.env.SCREENSHOT_DIR)await page.screenshot({path:process.env.SCREENSHOT_DIR+'/free-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});if(process.env.SCREENSHOT_DIR)await page.screenshot({path:process.env.SCREENSHOT_DIR+'/free-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('PASS: search with external services blocked; Sitagu English/Burmese; categories; empty; map fallback; events; private submission offline fallback; 12 responsive layouts; no paid Places API calls.');await context.close();
// Separate context verifies that cached local search really survives offline reloads.
const offline=await browser.newContext();const op=await offline.newPage();await op.goto(base);await op.waitForSelector('.place-card');await op.evaluate(async()=>{await navigator.serviceWorker.ready;});await op.reload();await op.waitForSelector('.place-card');await offline.setOffline(true);await op.reload();await op.waitForSelector('.place-card');await op.locator('#search').fill('Sitagu');await op.locator('#searchForm').evaluate(f=>f.requestSubmit());await op.waitForFunction(()=>!document.querySelector('#templeList').hasAttribute('aria-busy'));assert.match(await op.locator('#templeList').innerText(),/Sitagu/);console.log('PASS: offline reload and local search.');await browser.close();
