import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const b=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const ctx=await b.newContext({serviceWorkers:'block',viewport:{width:1440,height:1100}});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await ctx.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
const base=process.env.TMF_URL||'http://127.0.0.1:8766';await page.goto(base);await page.waitForSelector('.browse-name');
const data=JSON.parse(readFileSync(new URL('../public/directory.json',import.meta.url))).places;
for(const category of ['monastery','temple','organization']){assert.equal(await page.locator('#browse-'+category+' .browse-name').count(),data.filter(p=>p.categories.includes(category)).length);const names=await page.locator('#browse-'+category+' strong').allTextContents();const sorted=[...names].sort(new Intl.Collator('en',{sensitivity:'base',numeric:true}).compare);assert.deepEqual(names,sorted);}
assert.equal(await page.locator('#search').inputValue(),'');
await page.getByLabel('Monasteries starting letter').selectOption('S');const sitagu=page.locator('#browse-monastery').getByRole('button',{name:/Sitagu Buddhist Vihara/});await sitagu.click();await page.waitForSelector('dialog[open]');assert.match(await page.locator('#placeDialog').innerText(),/9001 Honeycomb/);assert.ok(await page.locator('#placeDialog').getByRole('link',{name:'Directions'}).getAttribute('href'));await page.keyboard.press('Escape');assert.equal(await page.locator('#placeDialog').isVisible(),false);assert.ok(await sitagu.evaluate(el=>document.activeElement===el));
await page.locator('#search').fill('Sitagu');await page.locator('#state').selectOption('TX');await page.waitForFunction(()=>!document.querySelector('#templeList').hasAttribute('aria-busy'));const url=page.url();const results=await page.locator('#templeList').innerText();
await page.locator('#browse-organization').getByRole('button',{name:/Burmese American Community Institute/}).click();assert.match(await page.locator('#placeDialog').innerText(),/Indianapolis/);await page.getByRole('button',{name:'Close place details'}).click();assert.equal(page.url(),url);assert.equal(await page.locator('#search').inputValue(),'Sitagu');assert.equal(await page.locator('#state').inputValue(),'TX');assert.equal(await page.locator('#templeList').innerText(),results);
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await sitagu.click();assert.ok(await page.locator('#placeDialog').evaluate(el=>el.scrollWidth<=el.clientWidth));await page.keyboard.press('Escape');}
await page.setViewportSize({width:1440,height:1100});await page.locator('#browse-area').scrollIntoViewIfNeeded();if(process.env.SCREENSHOT_DIR)await page.locator('#browse-area').screenshot({path:process.env.SCREENSHOT_DIR+'/browse-desktop.png'});await page.setViewportSize({width:390,height:844});await sitagu.click();if(process.env.SCREENSHOT_DIR)await page.screenshot({path:process.env.SCREENSHOT_DIR+'/browse-mobile-dialog.png'});await page.keyboard.press('Escape');
assert.deepEqual(errors,[]);console.log('PASS: all category names and alphabetical order; initial no-search browse; letter selection; place details; Escape/focus; unchanged search and URL; responsive name lists/dialog; no external services.');await b.close();
