import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const c=await browser.newContext({serviceWorkers:'block'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.env.TMF_URL||'http://127.0.0.1:8766';
const hosting=JSON.parse(await readFile(new URL('../firebase.json',import.meta.url),'utf8'));const csp=hosting.hosting.headers.at(-1).headers.find(h=>h.key==='Content-Security-Policy').value;
await p.addInitScript(()=>{window.cspErrors=[];document.addEventListener('securitypolicyviolation',e=>window.cspErrors.push(e.violatedDirective));});
const auth=`export const inMemoryPersistence={};const user={uid:'test-owner',email:'minmaung0307@gmail.com',getIdTokenResult:async()=>({claims:{email_verified:true,email:'minmaung0307@gmail.com'},signInProvider:'google.com',authTime:new Date().toISOString()})};const auth={currentUser:null};export const getAuth=()=>auth;export const setPersistence=async()=>{};export const onAuthStateChanged=(auth,cb)=>{cb(auth.currentUser);return ()=>{}};export class GoogleAuthProvider{setCustomParameters(){}};export const signInWithPopup=async()=>{auth.currentUser=user;return {user}};export const reauthenticateWithPopup=signInWithPopup;export const signOut=async()=>{auth.currentUser=null};`;
const photo='data:image/webp;base64,UklGRiIAAABXRUJQVlA4IBYAAAAwAQCdASoBAAEADsD+JaQAA3AAAAAA';
const cloud=`import {directoryPlace} from './place-model.js';let seq=0;const rows=new Map();const snap=ref=>({id:ref.id,exists:()=>rows.has(ref.path),data:()=>rows.get(ref.path)});const sdk={collection:(db,...path)=>({path:path.join('/')}),doc:(db,...path)=>{if(!path.length)path=[db.path,'new'+(++seq)];const full=path.join('/');return {path:full,id:full.split('/').at(-1)}},orderBy:()=>{},limit:()=>{},startAfter:()=>{},where:(key,op,value)=>({key,value}),query:(ref,...constraints)=>({...ref,constraints}),serverTimestamp:()=>({seconds:Date.now(),nanoseconds:0}),getDocFromServer:async ref=>snap(ref),getDocsFromServer:async ref=>{const docs=[...rows.keys()].filter(k=>k.startsWith(ref.path+'/')&&k.split('/').length===ref.path.split('/').length+1).map(path=>snap({path,id:path.split('/').at(-1)}));return {docs,size:docs.length}},setDoc:async(ref,data)=>rows.set(ref.path,data),getCountFromServer:async ref=>({data:()=>({count:[...rows.entries()].filter(([k,v])=>k.startsWith(ref.path+'/')&&ref.constraints.every(c=>!c||v[c.key]===c.value)).length})}),runTransaction:async(db,fn)=>fn({get:async ref=>snap(ref),set:(ref,data)=>rows.set(ref.path,data),delete:ref=>rows.delete(ref.path)})};export const getCloud=async()=>({app:{},db:{},sdk});export const cloudEventsEnabled=true;export const publishedEvents=async()=>[{id:'festival',title:'Community celebration',templeName:'Our temple',city:'Austin',state:'TX',address:'Test address',dateStart:'2026-12-01',dateEnd:'2026-12-01',description:'Join our community.',status:'published',cloud:true,hasPhoto:true,imageAlt:'Festival poster'}];const profile=directoryPlace('new-place',{name:'Community without website',category:'organization',city:'Austin',state:'TX',address:'123 Community Way',phone:'5125550100',website:'',description:'A welcoming community space.',hours:'Sundays, 9 AM to noon',aliasesText:'မြန်မာအဖွဲ့',status:'published',hasPhoto:false});export const publishedPlaces=async()=>[profile];export const publicPlace=async()=>profile;export const coverImage=async()=>({data:'${photo}',width:1,height:1});window.testRows=rows;`;
await c.route('**/*',async r=>{const u=new URL(r.request().url());if(u.pathname.endsWith('/cloud.js'))return r.fulfill({contentType:'text/javascript',body:cloud});if(u.pathname.endsWith('/firebase-auth.js'))return r.fulfill({contentType:'text/javascript',body:auth});if(!['127.0.0.1','localhost'].includes(u.hostname))return r.abort();if(/admin.*\.html$/.test(u.pathname)){const response=await r.fetch();return r.fulfill({response,headers:{...response.headers(),'Content-Security-Policy':csp}});}return r.continue();});
await p.goto(base+'/admin.html');await p.locator('#signIn').click();await p.locator('#eventForm').waitFor({state:'visible'});
const svg='<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300"><rect width="400" height="300" fill="#debe7d"/></svg>';
await p.locator('#coverFile').setInputFiles({name:'poster.svg',mimeType:'image/svg+xml',buffer:Buffer.from(svg)});await p.waitForFunction(()=>document.querySelector('#photoStatus').textContent.includes('Optimized cover'));assert.ok((await p.locator('#coverPreview').getAttribute('src')).startsWith('data:image/webp;'));
for(const[key,value]of Object.entries({title:'Photo event',templeName:'Test temple',city:'Austin',state:'TX',address:'Test address',dateStart:'2026-12-01',imageAlt:'Golden event poster'}))await p.locator(`[name=${key}]`).fill(value);await p.locator('[name=status]').selectOption('published');await p.locator('#saveEvent').click();await p.waitForFunction(()=>document.querySelector('#saveStatus').textContent.startsWith('Published.'));assert.ok(await p.evaluate(()=>[...testRows.entries()].some(([k,v])=>k.startsWith('tmf_media/')&&v.data.startsWith('data:image/webp;'))));
await p.getByRole('button',{name:'Edit',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('#coverPreview').hidden);await p.locator('#removeCover').click();await p.locator('#saveEvent').click();await p.waitForFunction(()=>document.querySelector('#saveStatus').textContent.startsWith('Published.'));assert.ok(await p.evaluate(()=>![...testRows.keys()].some(k=>k.startsWith('tmf_media/'))));
// Exercise real browser conversions, not mocked image processing.
for(const ext of ['png','jpeg','tiff','webp']){const bytes=await readFile(process.env.PHOTO_FIXTURES?process.env.PHOTO_FIXTURES+'/poster.'+ext:new URL('./fixtures/poster.'+ext,import.meta.url));const result=await p.evaluate(async({data,ext})=>{const {prepareImage}=await import('./media.js');return prepareImage(new File([Uint8Array.from(atob(data),c=>c.charCodeAt(0))],'poster.'+ext));},{data:bytes.toString('base64'),ext});assert.ok(result.data.startsWith('data:image/webp;'));assert.ok(result.data.length<=160023);}
const rejected=await p.evaluate(async()=>{const {prepareImage}=await import('./media.js');try{await prepareImage(new File(['<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>'],'bad.svg'));return false;}catch{return true;}});assert.equal(rejected,true);
assert.deepEqual(await p.evaluate(()=>window.cspErrors),[]);await p.goto(base+'/admin-places.html');await p.locator('#signIn').click();await p.locator('#eventForm').waitFor({state:'visible'});for(const[key,value]of Object.entries({name:'No website needed',city:'Austin',state:'TX',address:'Test address',description:'Our community',hours:'Sunday'}))await p.locator(`[name=${key}]`).fill(value);await p.locator('[name=category]').selectOption('organization');await p.locator('[name=status]').selectOption('published');await p.locator('#saveEvent').click();await p.waitForFunction(()=>document.querySelector('#saveStatus').textContent.startsWith('Published.'));assert.match(await p.locator('#adminEvents').innerText(),/No website needed/);
for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'profile admin overflow '+width);}
await p.goto(base+'/?place=community-new-place#discover');await p.locator('#placeDialog').waitFor({state:'visible'});assert.match(await p.locator('#placeDialogContent').innerText(),/Sundays, 9 AM/);assert.equal(await p.locator('#placeDialogContent').getByRole('link',{name:'Website ↗'}).count(),0);await p.locator('#closePlaceDialog').click();
await p.goto(base+'/#events');await p.getByText('Community celebration',{exact:true}).waitFor();await p.locator('.expandable-photo').first().waitFor();await p.locator('.expandable-photo').first().click();await p.getByRole('button',{name:'Close photo ×'}).click();await p.locator('.reactions').first().scrollIntoViewIfNeeded();const heart=p.getByRole('button',{name:'Love this: 0'});await heart.waitFor();await heart.click();await p.getByRole('button',{name:'Love this: 1'}).waitFor();await p.getByRole('button',{name:'Love this: 1'}).click();await p.getByRole('button',{name:'Love this: 0'}).waitFor();
for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'events overflow '+width);}
if(process.env.SCREENSHOT_DIR){await p.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';scrollTo(0,0)});await p.waitForTimeout(300);await p.screenshot({path:process.env.SCREENSHOT_DIR+'/v5-events.png',fullPage:true});}
assert.deepEqual(errors,[]);console.log('PASS: SVG/PNG/JPEG/TIFF/WebP conversion, hostile SVG rejection, atomic photo save/remove, website-free profile publishing, shared profile route, reaction add/remove, responsive profiles/events. Cloud transport mocked; rules tested separately.');await browser.close();
