import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const c=await browser.newContext({serviceWorkers:'block'}),p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.env.TMF_URL||'http://127.0.0.1:8766';
let seeded=[];
const auth=`export const inMemoryPersistence={};export const browserSessionPersistence={};const user={uid:'test-sender',email:'sender@example.com',getIdTokenResult:async()=>({claims:{email_verified:true,email:'sender@example.com'},signInProvider:'google.com',authTime:new Date().toISOString()})};const auth={currentUser:null,authStateReady:async()=>{}};export const getAuth=()=>auth;export const setPersistence=async()=>{};export const onAuthStateChanged=(auth,cb)=>{cb(auth.currentUser);return ()=>{}};export class GoogleAuthProvider{setCustomParameters(){}};export const signInWithPopup=async()=>{auth.currentUser=user;return {user}};export const reauthenticateWithPopup=signInWithPopup;export const signOut=async()=>{auth.currentUser=null};`;
function cloud(){return `let seq=0;const rows=new Map(${JSON.stringify(seeded)});const snap=ref=>({id:ref.id,exists:()=>rows.has(ref.path),data:()=>rows.get(ref.path)});const sdk={onSnapshot:(ref,next)=>{(ref.id?sdk.getDocFromServer(ref):sdk.getDocsFromServer(ref)).then(next);return ()=>{}},collection:(db,...path)=>({path:path.join('/')}),doc:(db,...path)=>{if(!path.length)path=[db.path,'new'+(++seq)];const full=path.join('/');return {path:full,id:full.split('/').at(-1)}},orderBy:()=>{},limit:()=>{},startAfter:()=>{},where:()=>{},query:(ref)=>ref,serverTimestamp:()=>({seconds:Date.now(),nanoseconds:0}),getDocFromServer:async ref=>snap(ref),getDocsFromServer:async ref=>{const docs=[...rows.keys()].filter(k=>k.startsWith(ref.path+'/')&&k.split('/').length===ref.path.split('/').length+1).map(path=>snap({path,id:path.split('/').at(-1)}));return {docs,size:docs.length}},runTransaction:async(db,fn)=>fn({get:async ref=>snap(ref),set:(ref,data)=>rows.set(ref.path,data),update:(ref,data)=>rows.set(ref.path,{...rows.get(ref.path),...data}),delete:ref=>rows.delete(ref.path)})};export const getCloud=async()=>({app:{},db:{},sdk});export const cloudEventsEnabled=true;export const publishedEvents=async()=>[];export const publishedPlaces=async()=>[];window.testRows=rows;`;}
await c.route('**/*',r=>{const u=new URL(r.request().url());if(u.pathname.endsWith('/cloud.js'))return r.fulfill({contentType:'text/javascript',body:cloud()});if(u.pathname.endsWith('/firebase-auth.js'))return r.fulfill({contentType:'text/javascript',body:auth});if(!['127.0.0.1','localhost'].includes(u.hostname))return r.abort();return r.continue();});
let downloads=0;p.on('download',()=>downloads++);await p.goto(base+'/#submit');assert.equal(await p.locator('#submissionSignOut').isVisible(),false);await p.getByRole('button',{name:'Sign in with Google',exact:true}).click();await p.locator('#submissionSignOut').waitFor({state:'visible'});await p.locator('[name=from_name]').fill('Private sender');await p.locator('[name=subject]').fill('Community event suggestion');await p.locator('[name=message]').fill('Public event description');await p.locator('[name=city]').fill('Austin');await p.locator('[name=state]').selectOption('TX');await p.getByRole('button',{name:'Send for review'}).click();await p.waitForFunction(()=>document.querySelector('#submitStatus').textContent.startsWith('Saved in the website'));assert.equal(await p.locator('[name=subject]').inputValue(),'');assert.equal(downloads,0);assert.equal(await p.locator('a[href^="mailto:"]').count(),0);seeded=await p.evaluate(()=>[...testRows.entries()]);assert.equal(seeded[0][1].status,'pending');assert.equal(seeded[0][1].reply_to,'sender@example.com');
await p.waitForFunction(()=>document.querySelector('#mySubmissionResult').textContent.includes('Waiting for review'));
await p.locator('[name=from_name]').fill('Private sender');await p.locator('[name=subject]').fill('Another suggestion');await p.locator('[name=message]').fill('Keep my form');await p.locator('[name=city]').fill('Austin');await p.locator('[name=state]').selectOption('TX');await p.getByRole('button',{name:'Send for review'}).click();await p.waitForFunction(()=>document.querySelector('#submitStatus').textContent.includes('already have a submission'));assert.equal(await p.locator('[name=message]').inputValue(),'Keep my form');
await p.locator('#submissionPurpose').selectOption('privacy');await p.locator('[name=subject]').fill('Privacy removal request');await p.getByRole('button',{name:'Send for review'}).click();await p.waitForFunction(()=>document.querySelector('#submitStatus').textContent.startsWith('Saved in the website'));seeded=await p.evaluate(()=>[...testRows.entries()]);assert.equal(seeded.length,2);await p.goto(base+'/admin.html');await p.locator('#signIn').click();await p.locator('.inbox-item').waitFor();assert.match(await p.locator('.inbox-item').innerText(),/Community event suggestion/);await p.getByRole('button',{name:'Review & publish event'}).click();assert.equal(await p.locator('[name=title]').inputValue(),'Community event suggestion');assert.equal(await p.locator('[name=status]').inputValue(),'draft');assert.ok(!(await p.locator('#eventForm').innerText()).includes('sender@example.com'));
await p.getByRole('button',{name:'Mark reviewed'}).click();await p.waitForFunction(()=>document.querySelector('.inbox-item').textContent.includes('reviewed ·'));assert.equal(await p.evaluate(()=>testRows.get('tmf_submissions/test-sender').status),'reviewed');
for(const [key,value]of Object.entries({templeName:'Test temple',city:'Kitty Hawk',state:'NC',address:'Public address',dateStart:'2026-10-23'}))await p.locator(`[name=${key}]`).fill(value);
await p.locator('#publishEvent').click();await p.waitForFunction(()=>document.querySelector('#saveStatus').textContent.startsWith('Published.'));assert.equal(await p.evaluate(()=>testRows.get('tmf_submissions/test-sender').publicationCollection),'tmf_events');
assert.equal(await p.locator('#eventForm').isVisible(),false);await p.getByRole('button',{name:'Edit / Publish',exact:true}).click();await p.locator('#publishEvent').click();await p.waitForFunction(()=>document.querySelector('#saveStatus').textContent.startsWith('Published.'));assert.equal(await p.locator('.admin-event-row').count(),1);
await p.locator('#refreshInbox').click();await p.locator('.inbox-link-panel summary').click();for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'expanded inbox overflow '+width);const aligned=await p.locator('.inbox-link-controls').evaluate(el=>{const a=el.querySelector('select').getBoundingClientRect(),b=el.querySelector('button').getBoundingClientRect();return innerWidth<=480?b.top>=a.bottom:Math.abs(a.bottom-b.bottom)<2;});assert.ok(aligned,'link controls alignment '+width);await p.screenshot({path:'/workspace/scratch/a573278d97fb/output/inbox-link-'+width+'.png',fullPage:true});}const beforeLink=await p.evaluate(()=>JSON.stringify([...testRows].filter(([key])=>key.startsWith('tmf_events/'))));await p.getByLabel('Link existing event',{exact:true}).selectOption({index:1});await p.getByRole('button',{name:'Link existing event',exact:true}).click();await p.waitForFunction(()=>document.querySelector('#inboxStatus').textContent.includes('Live inbox'));assert.equal(await p.evaluate(()=>JSON.stringify([...testRows].filter(([key])=>key.startsWith('tmf_events/')))),beforeLink);
await p.locator('#inboxKind').selectOption('tmf_privacy_requests');await p.getByText('Privacy removal request',{exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Review & publish event'}).count(),0);
for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
await p.locator('#signOut').click();assert.equal(await p.locator('#inboxItems').innerText(),'');assert.equal(await p.locator('#adminWorkspace').isVisible(),false);assert.deepEqual(errors,[]);
for(const name of ['config.js','cloud-config.js','admin.js','app.js','index.html']){const text=await readFile(new URL('../public/'+name,import.meta.url),'utf8');assert.ok(!/minmaung0307|panna07/.test(text));if(name!=='app.js')assert.ok(!text.includes('mailto:'));}
console.log('PASS: direct private submission without download/email, own status, pending duplicate rejection, private admin review/draft, no automatic publication, responsive inbox, sign-out cleanup and no owner email in public source. Cloud transport mocked; server rules tested separately.');await browser.close();
