import assert from 'node:assert/strict';import {mkdir} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const base=process.env.TMF_URL||'http://127.0.0.1:8780';
const auth=`const listeners=new Set(),user={uid:'test-member',displayName:'May Thiri',email:'may@example.com'};const auth={currentUser:sessionStorage.getItem('fixture-user')?user:null,authStateReady:async()=>{}};export const browserSessionPersistence={};export const getAuth=()=>auth;export const setPersistence=async()=>{};export const onAuthStateChanged=(a,cb)=>{listeners.add(cb);queueMicrotask(()=>cb(a.currentUser));return ()=>listeners.delete(cb)};export class GoogleAuthProvider{setCustomParameters(){}}export const signInWithPopup=async()=>{sessionStorage.setItem('fixture-user','yes');auth.currentUser=user;listeners.forEach(cb=>cb(user));return {user}};export const signOut=async()=>{sessionStorage.removeItem('fixture-user');auth.currentUser=null;listeners.forEach(cb=>cb(null))};`;
const cloud=`
let rows=new Map(JSON.parse(localStorage.getItem('fixture-db')||'[]')),listeners=new Set(),seq=0;
const snap=path=>({id:path.split('/').at(-1),metadata:{fromCache:false},exists:()=>rows.has(path),data:()=>rows.get(path)});
const querySnap=q=>({metadata:{fromCache:false},docs:[...rows.keys()].filter(k=>k.startsWith(q.path+'/')&&k.split('/').length===q.path.split('/').length+1).map(snap),size:rows.size});
const emit=()=>{localStorage.setItem('fixture-db',JSON.stringify([...rows]));for(const [ref,next]of listeners)next(ref.query?querySnap(ref):snap(ref.path));};
const sdk={doc:(first,...parts)=>({path:parts.length?parts.join('/'):first.path+'/new-'+Date.now()+'-'+(++seq)}),collection:(db,...parts)=>({path:parts.join('/')}),query:(ref,...rest)=>({...ref,query:true}),orderBy:()=>{},limit:()=>{},serverTimestamp:()=>({seconds:Date.now(),nanoseconds:++seq}),getDocFromServer:async ref=>{if(ref.path==='tmf_admin_access/check')throw Object.assign(Error('member'),{code:'permission-denied'});return snap(ref.path)},onSnapshot:(ref,next)=>{const pair=[ref,next];listeners.add(pair);queueMicrotask(()=>next(ref.query?querySnap(ref):snap(ref.path)));return ()=>listeners.delete(pair);},runTransaction:async(db,fn)=>{if(window.fixtureDelay)await new Promise(r=>setTimeout(r,window.fixtureDelay));if(window.fixtureReject){window.fixtureReject=false;throw Error('Test save rejected');}await fn({get:async ref=>snap(ref.path),set:(ref,data)=>rows.set(ref.path,data),update:(ref,data)=>rows.set(ref.path,{...rows.get(ref.path),...data}),delete:ref=>rows.delete(ref.path)});emit();}};
export const getCloud=async()=>({app:{},db:{},sdk});export const cloudEventsEnabled=true;export const publishedPlaces=async()=>[];export const watchPublishedEvents=async next=>{window.live=next;next([]);return ()=>{}};export const watchPublicEvent=async(id,next)=>{window.detail=next;return ()=>{}};`;
try{const c=await b.newContext({serviceWorkers:'block'});await c.route('**/*',r=>{const u=new URL(r.request().url());if(u.pathname.endsWith('/cloud.js'))return r.fulfill({contentType:'text/javascript',body:cloud});if(u.pathname.endsWith('/firebase-auth.js'))return r.fulfill({contentType:'text/javascript',body:auth});if(!['localhost','127.0.0.1'].includes(u.hostname))return r.abort();return r.continue();});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/profile.html');await p.getByRole('button',{name:'Sign in with Google',exact:true}).click();await p.locator('#privateWorkspace').waitFor({state:'visible'});assert.equal(await p.locator('#manageSite').isVisible(),false);
 await p.getByRole('button',{name:'Edit profile',exact:true}).click();await p.locator('[name=displayName]').fill('May Thiri');await p.locator('[name=location]').fill('Austin, Texas');await p.locator('[name=phone]').fill('+1 555 010 2222');await p.locator('[name=bio]').fill('Community volunteer and meditation learner.');await p.locator('#avatarFile').setInputFiles({name:'avatar.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aB9sAAAAASUVORK5CYII=','base64')});await p.waitForFunction(()=>document.querySelector('#profileSaveStatus').textContent.includes('Photo ready'));await p.locator('#saveProfile').click();await p.waitForFunction(()=>document.querySelector('#profileSaveStatus').textContent==='Profile saved.');assert.equal(await p.locator('#profilePanel').isVisible(),false);assert.equal(await p.locator('#boardPanel').isVisible(),true);assert.match(await p.locator('#profileAvatar').getAttribute('src'),/^data:image\/webp/);await p.reload();await p.locator('#profileName').getByText('May Thiri',{exact:true}).waitFor();assert.equal(await p.locator('#profileLocation').innerText(),'Austin, Texas');assert.equal(await p.locator('#profilePhone').innerText(),'+1 555 010 2222');assert.equal(await p.locator('#profileAbout').innerText(),'Community volunteer and meditation learner.');
 for(const [title,details]of [['Plan a retreat visit','Check the course schedule and make time to pause.'],['Help at the community gathering','Bring a little kindness.'],['Call the center','Confirm visiting arrangements.']]){await p.locator('#addTask').click();await p.locator('.workspace-dialog [name=title]').fill(title);await p.locator('.workspace-dialog [name=details]').fill(details);await p.getByRole('button',{name:'Save task',exact:true}).click();await p.locator('.workspace-dialog').waitFor({state:'detached'});}
 assert.equal(await p.locator('.task-card').count(),3);const first=p.locator('.task-card').filter({hasText:'Plan a retreat visit'});await first.dragTo(p.locator('.status-doing'),{sourcePosition:{x:20,y:20},targetPosition:{x:50,y:60}});await p.waitForFunction(()=>document.querySelector('.status-doing').textContent.includes('Plan a retreat visit'));
 await p.getByLabel('Edit task: Plan a retreat visit',{exact:true}).click();await p.locator('.workspace-dialog [name=title]').fill('Plan a weekend retreat');await p.getByRole('button',{name:'Save task',exact:true}).click();await p.locator('.workspace-dialog').waitFor({state:'detached'});await p.getByLabel('Move task: Call the center',{exact:true}).selectOption('done');await p.waitForFunction(()=>document.querySelector('#completedTasks').textContent==='1 / 3');

 // Hold the server for two seconds: the selected card must move synchronously, without rebuilding its DOM.
 await p.evaluate(()=>{window.fixtureDelay=2000;const select=document.querySelector('[aria-label="Move task: Call the center"]');window.keptSelect=select;window.keptCard=select.closest('.task-card');window.beforeBoardY=document.querySelector('#taskBoard').getBoundingClientRect().top;});
 const immediate=await p.evaluate(()=>{const select=window.keptSelect,start=performance.now();select.value='doing';select.dispatchEvent(new Event('change',{bubbles:true}));return {status:select.closest('.kanban-column').dataset.status,elapsed:performance.now()-start,same:select===window.keptSelect,y:document.querySelector('#taskBoard').getBoundingClientRect().top};});assert.equal(immediate.status,'doing');assert.ok(immediate.elapsed<100);assert.equal(immediate.same,true);assert.equal(immediate.y,await p.evaluate(()=>window.beforeBoardY));
 await p.getByLabel('Move task: Call the center',{exact:true}).selectOption('todo');await p.getByLabel('Move task: Call the center',{exact:true}).selectOption('done');assert.equal(await p.locator('.status-done .task-card').filter({hasText:'Call the center'}).count(),1);await p.waitForFunction(()=>window.keptCard.getAttribute('aria-busy')==='false');assert.equal(await p.evaluate(()=>window.keptSelect===document.querySelector('[aria-label="Move task: Call the center"]')),true);
 await p.evaluate(()=>{window.fixtureDelay=150;window.fixtureReject=true;});await p.getByLabel('Move task: Call the center',{exact:true}).selectOption('doing');await p.waitForFunction(()=>document.querySelector('#taskStatus').textContent.includes('Move could not be saved'));assert.equal(await p.locator('.status-done .task-card').filter({hasText:'Call the center'}).count(),1);await p.evaluate(()=>{window.fixtureDelay=0;});
 await p.getByRole('button',{name:'Notes',exact:true}).click();await p.locator('#addRecord').click();assert.equal(await p.locator('.workspace-dialog [name=date]').count(),0);await p.locator('.workspace-dialog [name=body]').fill('A quiet Sunday\nA note to remember. <script>not HTML</script>');await p.getByRole('button',{name:'Save note',exact:true}).click();await p.locator('.workspace-dialog').waitFor({state:'detached'});assert.match(await p.locator('#recordsList').innerText(),/<script>not HTML<\/script>/);assert.equal(await p.locator('#recordsList script').count(),0);await p.reload();await p.getByRole('button',{name:'Notes',exact:true}).click();await p.getByLabel('Edit note: A quiet Sunday',{exact:true}).click();await p.locator('.workspace-dialog [name=body]').fill('Updated reflection');await p.getByRole('button',{name:'Save note',exact:true}).click();await p.locator('.workspace-dialog').waitFor({state:'detached'});await p.getByLabel('Delete note: A quiet Sunday',{exact:true}).click();await p.getByRole('button',{name:'Delete permanently',exact:true}).click();await p.locator('.workspace-dialog').waitFor({state:'detached'});assert.equal(await p.locator('.record-card').count(),0);
 await p.getByRole('button',{name:'Task board',exact:true}).click();for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:1000});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'workspace overflow '+width);await p.screenshot({path:'/workspace/scratch/a573278d97fb/output/workspace-'+width+'.png',fullPage:true});}
 await p.getByLabel('Delete task: Help at the community gathering',{exact:true}).click();await p.getByRole('button',{name:'Delete permanently',exact:true}).click();await p.locator('.workspace-dialog').waitFor({state:'detached'});assert.equal(await p.locator('.task-card').count(),2);await p.locator('#profileSignOut').click();await p.locator('#privateWorkspace').waitFor({state:'hidden'});assert.equal(await p.locator('.task-card').count(),0);await p.reload();await p.getByRole('button',{name:'Sign in with Google',exact:true}).waitFor();assert.equal(await p.locator('#privateWorkspace').isVisible(),false);
 await p.goto(base+'/#events');await p.waitForFunction(()=>window.live);await p.evaluate(()=>window.live([{id:'one',cloud:true,title:'Community gathering',dateStart:'2026-11-01',dateEnd:'2026-11-01',templeName:'Our community',city:'Austin',state:'TX',address:'Community hall',description:'A warm welcome for everyone.'}]));await p.locator('.event-card h3').click();await p.locator('.event-details-dialog .event-qr').waitFor();assert.ok(await p.locator('.event-qr').evaluate(img=>img.naturalWidth>0));await p.keyboard.press('Escape');await p.locator('.event-details-dialog').waitFor({state:'detached'});await p.locator('.event-card').focus();await p.keyboard.press('Enter');await p.locator('.event-details-dialog').waitFor();await p.keyboard.press('Escape');
 await p.goto(base+'/#discover');await p.getByRole('button',{name:/Retreat centers/}).click();await p.waitForFunction(()=>document.querySelector('#templeList').textContent.includes('Dhamma Dharā'));assert.match(await p.locator('.hero h1').innerText(),/Home/);assert.match(await p.locator('.hero-reconnect').innerText(),/Reconnect with your community/);for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:1000});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'directory overflow '+width);await p.screenshot({path:'/workspace/scratch/a573278d97fb/output/directory-'+width+'.png',fullPage:true});}

 for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:1000});await p.goto(base+'/');const original=await p.locator('.site-header nav a').evaluateAll(items=>items.map(e=>({text:e.textContent,x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y,width:e.getBoundingClientRect().width})));await p.goto(base+'/profile.html');const profileNav=await p.locator('.site-header nav a').evaluateAll(items=>items.map(e=>({text:e.textContent,x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y,width:e.getBoundingClientRect().width})));assert.deepEqual(profileNav,original);}
 await p.goto(base+'/#submit');await p.locator('[name=event_type]').selectOption('__create_event_type__');await p.getByLabel('Event type name',{exact:true}).fill('Dhamma Q&A');await p.getByRole('button',{name:'Create type',exact:true}).click();assert.equal(await p.locator('[name=event_type]').inputValue(),'Dhamma Q&A');assert.equal(await p.locator('[name=event_type]').evaluate(el=>new FormData(el.form).get('event_type')),'Dhamma Q&A');await p.reload();await p.locator('[name=event_type] option').filter({hasText:'Dhamma Q&A'}).waitFor({state:'attached'});await p.locator('[name=event_type]').selectOption('Dhamma Q&A');await p.locator('[name=event_type]').selectOption('__create_event_type__');await p.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await p.locator('[name=event_type]').inputValue(),'Dhamma Q&A');
 await p.goto(base+'/#discover');await p.evaluate(()=>window.navigationMarker=true);await p.getByRole('link',{name:'My space',exact:true}).click();await p.getByRole('button',{name:'Sign in with Google',exact:true}).click();await p.getByRole('button',{name:'Edit profile',exact:true}).click();await p.locator('[name=bio]').fill('Unsaved draft stays here');await p.getByRole('link',{name:'Events',exact:true}).click();await p.getByRole('link',{name:'My space',exact:true}).click();assert.equal(await p.evaluate(()=>window.navigationMarker),true);assert.equal(await p.locator('[name=bio]').inputValue(),'Unsaved draft stays here');assert.deepEqual(await p.locator('.site-header nav a').allTextContents(),['Discover','Events','Contribute','My space']);assert.equal(await p.locator('.site-header nav a svg').count(),4);for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'embedded workspace overflow '+width);}await p.getByRole('link',{name:'Contribute',exact:true}).click();await p.getByRole('button',{name:'Sign out',exact:true}).click();await p.getByRole('link',{name:'My space',exact:true}).click();await p.locator('#privateWorkspace').waitFor({state:'hidden'});
 assert.deepEqual(errors,[]);console.log('PASS immediate task moves under 2s server latency, rapid moves, failed-save rollback, stable DOM and menu coordinates; profile save closes editor; simple notes; custom event types; existing flows.');
}finally{await b.close();}
